/* ╔══════════════════════════════════════════════════════════╗
 *  steelSectionsReader.js
 *
 *  CSV parsers for Blue Book steel section data. Each parser
 *  fetches a CSV, builds composite header keys, and returns
 *  an array of section objects with explicit property aliases.
 *
 *  Parsers:
 *    loadSections()          → UB, UC, PFC, EA, UA
 *    loadHollowSections()    → SHS, RHS
 *    loadCircularSections()  → CHS
 * ╚══════════════════════════════════════════════════════════╝ */


/* ═══════════════════════════════════════════════════════════
 *  OPEN SECTIONS (UB / UC / PFC / EA / UA)
 * ═══════════════════════════════════════════════════════════ */

export async function loadSections(url) {
  const res  = await fetch(url);
  const text = await res.text();

  const rows = text.split("\n").map(r => r.split(","));

  /* ─── Composite Header Keys (rows 5–7) ─────────────────── */

  const headerRow1 = rows[4];
  const headerRow2 = rows[5];
  const headerRow3 = rows[6];

  const keys = headerRow3.map((_, i) => {
    return [headerRow1[i], headerRow2[i], headerRow3[i]]
      .map(s => (s || "").trim())
      .filter(Boolean)
      .join("_")
      .replace(/\s+/g, "_")
      .replace(/[^a-zA-Z0-9_]/g, "")
      .toLowerCase();
  });

  /* ─── Data Row Parsing ─────────────────────────────────── */

  const DATA_START  = 7;
  let currentSeries = "";
  const sections    = [];

  for (let i = DATA_START; i < rows.length; i++) {
    const row = rows[i];
    if (!row || row.length < 8) continue;

    const namePart = (row[0] || "").trim();
    const subPart  = (row[1] || "").trim();

    if (namePart) currentSeries = namePart;

    /* ·· Display name construction ··························· */

    // UB / UC / PFC: subPart starts with "x" → "430x100 x64"
    // EA / UA:       subPart is a bare number → "200x200 x 24.0"
    const isAngle = subPart && !/^x/i.test(subPart);

    const fullSection = (() => {
      if (!subPart) return currentSeries;
      const raw = isAngle
        ? `${currentSeries} x ${subPart}`
        : `${currentSeries} ${subPart}`;
      return raw.replace(/\s+/g, " ").trim();
    })();

    if (!fullSection) continue;
    if (!/^\d+\s*x\s*\d+\s*x\s*[\d.]+$/.test(fullSection)) continue;

    /* ·· Core geometry ······································· */

    const obj = { section: fullSection, mass: parseFloat(row[3]) };

    if (isAngle) {
      const sizeMatch = currentSeries.match(/^(\d+)\s*x\s*(\d+)$/);
      obj.h  = sizeMatch ? parseFloat(sizeMatch[1]) : NaN;
      obj.b  = sizeMatch ? parseFloat(sizeMatch[2]) : NaN;
      obj.t  = parseFloat(subPart);
      obj.tw = obj.t;
      obj.tf = obj.t;
      obj.r1 = parseFloat(row[4]);
      obj.r2 = parseFloat(row[5]);

      /* ·· Angle-specific property aliases ···················· */

      const isEqualAngle = (obj.h === obj.b);

      if (isEqualAngle) {
        obj.centroidC          = parseFloat(row[6]);
        obj.secondMomentYy     = parseFloat(row[7]);
        obj.secondMomentZz     = parseFloat(row[7]);
        obj.elasticModulusYy   = parseFloat(row[13]);
        obj.elasticModulusZz   = parseFloat(row[13]);
        obj.torsionalConstant  = parseFloat(row[14]);
        obj.areaCm2            = parseFloat(row[16]);
      } else {
        obj.centroidCy         = parseFloat(row[6]);
        obj.centroidCz         = parseFloat(row[7]);
        obj.secondMomentYy     = parseFloat(row[8]);
        obj.secondMomentZz     = parseFloat(row[9]);
        obj.elasticModulusYy   = parseFloat(row[16]);
        obj.elasticModulusZz   = parseFloat(row[17]);
        obj.tanTheta           = parseFloat(row[18]);
        obj.torsionalConstant  = parseFloat(row[19]);
        obj.areaCm2            = parseFloat(row[23]);
      }
    } else {
      obj.h  = parseFloat(row[4]);
      obj.b  = parseFloat(row[5]);
      obj.tw = parseFloat(row[6]);
      obj.tf = parseFloat(row[7]);
      obj.r  = parseFloat(row[8]);
      obj.d  = parseFloat(row[9]);
    }

    /* ·· Autogenerated property map ··························· */

    for (let j = 2; j < row.length; j++) {
      const key = keys[j];
      if (!key) continue;
      const val = parseFloat(row[j]);
      obj[key] = Number.isNaN(val) ? row[j] : val;
    }

    /* ·· I-section & channel aliases (UB / UC / PFC only) ···· */

    if (!isAngle) {
      obj.cwOverTw = parseFloat(row[10]);
      obj.cfOverTf = parseFloat(row[11]);

      obj.e0                = parseFloat(row[12]);
      obj.secondMomentYy    = parseFloat(row[18]);
      obj.secondMomentZz    = parseFloat(row[19]);
      obj.radiusGyrationYy  = parseFloat(row[20]);
      obj.radiusGyrationZz  = parseFloat(row[21]);
      obj.elasticModulusYy  = parseFloat(row[22]);
      obj.elasticModulusZz  = parseFloat(row[23]);
      obj.plasticModulusYy  = parseFloat(row[24]);
      obj.plasticModulusZz  = parseFloat(row[25]);
      obj.warpingConstant   = parseFloat(row[28]);
      obj.torsionalConstant = parseFloat(row[29]);
      obj.areaCm2           = parseFloat(row[30]);
    }

    sections.push(obj);
  }

  return sections;
}


/* ═══════════════════════════════════════════════════════════
 *  HOLLOW SECTIONS (SHS / RHS)
 * ═══════════════════════════════════════════════════════════ */

export async function loadHollowSections(url) {
  const res  = await fetch(url);
  const text = await res.text();
  const rows = text.split("\n").map(r => r.split(","));

  /* ─── Composite Header Keys (rows 7–9) ─────────────────── */

  const headerRow1 = rows[6];
  const headerRow2 = rows[7];
  const headerRow3 = rows[8];

  const keys = headerRow3.map((_, i) => {
    return [headerRow1[i], headerRow2[i], headerRow3[i]]
      .map(s => (s || "").trim())
      .filter(Boolean)
      .join("_")
      .replace(/\s+/g, "_")
      .replace(/[^a-zA-Z0-9_]/g, "")
      .toLowerCase();
  });

  /* ─── Data Row Parsing ─────────────────────────────────── */

  const DATA_START  = 10;
  let currentSeries = "";
  const sections    = [];

  for (let i = DATA_START; i < rows.length; i++) {
    const row = rows[i];
    if (!row || row.length < 6) continue;

    const namePart = (row[0] || "").trim();
    const subPart  = (row[1] || "").trim();

    if (namePart) currentSeries = namePart;

    /* ·· Display name construction ··························· */

    const fullSection = (() => {
      if (!subPart) return currentSeries;
      return `${currentSeries} x ${subPart}`.replace(/\s+/g, " ").trim();
    })();

    if (!fullSection) continue;
    if (!/^\d+\s*x\s*\d+\s*x\s*[\d.]+$/.test(fullSection)) continue;

    /* ·· Core geometry ······································· */

    const sizeMatch = currentSeries.match(/^(\d+)\s*x\s*(\d+)$/);
    const h = sizeMatch ? parseFloat(sizeMatch[1]) : NaN;
    const b = sizeMatch ? parseFloat(sizeMatch[2]) : NaN;
    const t = parseFloat(subPart);

    if (isNaN(h) || isNaN(b) || isNaN(t)) continue;

    const obj = {
      section: fullSection,
      mass:    parseFloat(row[3]),
      h, b, t,
      tw: t,
      tf: t,
    };

    /* ·· Autogenerated property map ··························· */

    for (let j = 2; j < row.length; j++) {
      const key = keys[j];
      if (!key) continue;
      const val = parseFloat(row[j]);
      obj[key] = Number.isNaN(val) ? row[j] : val;
    }

    /* ·· SHS vs RHS property aliases ························· */

    const isSHS = (h === b);

    if (isSHS) {
      obj.areaCm2           = parseFloat(row[4]);
      obj.ctRatio           = parseFloat(row[5]);
      obj.secondMomentYy    = parseFloat(row[6]);
      obj.secondMomentZz    = parseFloat(row[6]);
      obj.elasticModulusYy  = parseFloat(row[8]);
      obj.elasticModulusZz  = parseFloat(row[8]);
      obj.plasticModulusYy  = parseFloat(row[9]);
      obj.plasticModulusZz  = parseFloat(row[9]);
      obj.torsionalConstant = parseFloat(row[10]);
    } else {
      obj.areaCm2           = parseFloat(row[4]);
      obj.cwOverTw          = parseFloat(row[5]);
      obj.cfOverTf          = parseFloat(row[6]);
      obj.secondMomentYy    = parseFloat(row[7]);
      obj.secondMomentZz    = parseFloat(row[8]);
      obj.elasticModulusYy  = parseFloat(row[11]);
      obj.elasticModulusZz  = parseFloat(row[12]);
      obj.plasticModulusYy  = parseFloat(row[13]);
      obj.plasticModulusZz  = parseFloat(row[14]);
      obj.torsionalConstant = parseFloat(row[15]);
    }

    sections.push(obj);
  }

  return sections;
}


/* ═══════════════════════════════════════════════════════════
 *  CIRCULAR HOLLOW SECTIONS (CHS)
 * ═══════════════════════════════════════════════════════════ */

export async function loadCircularSections(url) {
  const res  = await fetch(url);
  const text = await res.text();
  const rows = text.split("\n").map(r => r.split(","));

  /* ─── Composite Header Keys (rows 7–9) ─────────────────── */

  const headerRow1 = rows[6];
  const headerRow2 = rows[7];
  const headerRow3 = rows[8];

  const keys = headerRow3.map((_, i) => {
    return [headerRow1[i], headerRow2[i], headerRow3[i]]
      .map(s => (s || "").trim())
      .filter(Boolean)
      .join("_")
      .replace(/\s+/g, "_")
      .replace(/[^a-zA-Z0-9_]/g, "")
      .toLowerCase();
  });

  /* ─── Data Row Parsing ─────────────────────────────────── */

  const DATA_START    = 10;
  let currentDiameter = "";
  const sections      = [];

  for (let i = DATA_START; i < rows.length; i++) {
    const row = rows[i];
    if (!row || row.length < 6) continue;

    const namePart = (row[0] || "").trim();
    const subPart  = (row[1] || "").trim();

    if (namePart) currentDiameter = namePart;
    if (!subPart) continue;

    /* ·· Display name construction ··························· */

    const fullSection = `${currentDiameter} x ${subPart}`
      .replace(/\s+/g, " ").trim();

    if (!fullSection) continue;
    if (!/^[\d.]+\s*x\s*[\d.]+$/.test(fullSection)) continue;

    /* ·· Core geometry ······································· */

    const d = parseFloat(currentDiameter);
    const t = parseFloat(subPart);
    if (isNaN(d) || isNaN(t)) continue;

    const obj = {
      section: fullSection,
      mass:    parseFloat(row[3]),
      d, t,
      h:  d,
      b:  d,
      tw: t,
      tf: t,
    };

    /* ·· Autogenerated property map ··························· */

    for (let j = 2; j < row.length; j++) {
      const key = keys[j];
      if (!key) continue;
      const val = parseFloat(row[j]);
      obj[key] = Number.isNaN(val) ? row[j] : val;
    }

    /* ·· CHS property aliases ································ */

    obj.areaCm2           = parseFloat(row[4]);
    obj.dtRatio           = parseFloat(row[5]);
    obj.secondMoment      = parseFloat(row[6]);
    obj.radiusGyration    = parseFloat(row[7]);
    obj.elasticModulus    = parseFloat(row[8]);
    obj.plasticModulus    = parseFloat(row[9]);
    obj.torsionalConstant = parseFloat(row[10]);
    obj.torsionalModulus  = parseFloat(row[11]);

    sections.push(obj);
  }

  return sections;
}